### ISSUE TITLE
Remove glyph ✔️ from Sarasa Mono/Term

### ISSUE THREAD

**Issue by yzhang-gh** [be5invis/Sarasa-Gothic#116]
From https://github.com/be5invis/Sarasa-Gothic/issues/82#issuecomment-541375901.

![image](https://user-images.githubusercontent.com/7588612/66711442-6d031b00-edbe-11e9-881a-68aff94e6a49.png)

cc @polarathene

**Comment by polarathene** [comment]
Gothic/UI aren't providing the text glyph, only Mono/Term. This is why you have success with you're `Segoe UI Emoji` fallback for them but not Mono/Term versions.

The general behaviour for rendering glyphs(be that symbols/emoji), is that if the given font has those glyphs, then no fallback will be searched for by the system, regardless of any Variation Selector(VS) being present(B column has VS16 which has codepoint 0xFE0F). However, if a fallback is searched for, these VS usually are taken into account, and thus you get different/appropriate fallbacks.

So Consolas is probably lacking the symbol too given the screenshot. The selection behaviour when the emoji font is also provided via a list(not always an option depending on app), has the font list sequentially used as fallback before querying the system for one. Since `Segoe UI Emoji` covers the symbol when the prior font does not, it is applied to both variants.

You can further confirm all variants are prioritized this way by using the following:

```
Check Mark(0x2714) => A(default presentation, no VS), B(+VS16), C(+VS15)

A: ✔ B: ✔️ C: ✔︎
B: ✔️ C: ✔︎ A: ✔
C: ✔︎ B: ✔️ A: ✔
A: ✔ B: ✔️ C: ✔︎ 
B: ✔️ A: ✔ C: ✔︎ 
```

`C` in this case is using VS15(0xFE0E) which should indicate preference for text presentation, but might be less supported compared to default and VS16(see [here](https://en.wikipedia.org/wiki/Emoji#Emoji_versus_text_presentation) for some emoji that have colour/emoji as default representation and VS15 can render text version depending on app/platform, Noto Sans Symbols2 covers the hour glass 231B as a text emoji for example). Code fence is used since Github will convert the VS16 variant into an image otherwise preventing copy/paste.

✔️ [(Heavy) Check Mark](https://emojipedia.org/heavy-check-mark/), codepoint 2714 has [two official forms in unicode](https://unicode.org/Public/emoji/12.0/emoji-test.txt), it is categorized in the [unicode block for Dingbats](https://en.wikipedia.org/wiki/Dingbat#Emoji) which also mentions default presentation of text.

**Comment by polarathene** [comment]
@yzhang-gh Have you considered that since this font is afaik, a composition of Iosevka and Source Han Sans, that you could instead try a build of Iosevka font without these symbols, with your CJK ideographs falling back with Source Han Mono(probably better than the half-width Source Han Sans?), and your emoji font preference as the last font?

I think this would be the advice that @be5invis agrees with? You can see what Iosevka covers [here](https://typeof.net/Iosevka/specimen.html). I'm not sure if Sarasa Gothic makes any other changes beyond combining the two fonts, if none this should be the solution for you?

I'm not sure if this is something Iosevka currently supports easy modification of, it seems to be referenced for build/generation of fonts [here](https://github.com/be5invis/Iosevka/blob/f7b6c666ee2d4571771206a17205e95de13c5bbf/gen/buildglyphs.ptl#L225), and [defined in this PTL file](https://github.com/be5invis/Iosevka/blob/master/glyphs/symbol-other.ptl)(What is a PTL file anyway? Is it a custom extension, do you edit the text file directly or is that generated from some GUI software? Google didn't have any clear answers here).

Presumably @be5invis would have this configurable in parameters.toml/variants.toml and you'd define the variant without symbols in a build-plan.toml? I don't know the codebase well enough to figure out where this separation is happening(unless that's happening in the Sarasa Gothic project code instead to exclude Gothic/UI from symbols? Ioveska symbols all seem to be related to requests [here](https://github.com/be5invis/Iosevka/issues/81)(for the missing ones, be5invis could probably source them from a font like Noto Sans Symbols2, such as that hour glass request. **EDIT:** Nvm, [he handcodes the glyphs..](https://github.com/be5invis/Iosevka/issues/90)), it doesn't list all prior symbols though as the checkmark isn't there.

**Comment by be5invis** [comment]
U+2714 is requested **three years ago**: https://github.com/be5invis/Iosevka/issues/112
I may add an option in Iosevka that "knocks out" all Emoji-related code points.
Close as external.

**Comment by yzhang-gh** [comment]
That would be great 👍
