### ISSUE TITLE
What's the right position to reinstall fonts?

### ISSUE THREAD

**Issue by CrotchBurnt** [be5invis/Sarasa-Gothic#148]
Whenever I try to delete the present files, it always shows resources in use. I have to reboot into safe mode, then delete fonts and install the new ones.
Is there a proper way to do this?

**Comment by Lemmingh** [comment]
Hi, did you mean this:

![2020-04-06_Fonts cannot be deleted because it's in use](https://user-images.githubusercontent.com/43396014/80098424-6fc99e80-859f-11ea-96ad-c266496aa35e.png)

Please try to

* Close ***all*** the applications. Remember to check background apps if possible.
* Update to the latest version of Windows 10.

Then, go to **Windows Settings**, and uninstall the fonts.

Good luck.
