### ISSUE TITLE
Sarasa _intensively_ uses TT hints to maximize clarity — so a badly implemented rasterizer may become slow when scaling them. Perhaps an unhinted edition in the future...

### ISSUE THREAD

**Issue by hsiungwang** [be5invis/Sarasa-Gothic#219]
Sarasa _intensively_ uses TT hints to maximize clarity — so a badly implemented rasterizer may become slow when scaling them. Perhaps an unhinted edition in the future...

_Originally posted by @be5invis in https://github.com/be5invis/Sarasa-Gothic/issues/218#issuecomment-757409436_

unhinted edition? I am very much looking forward to such a version. If it is released, it will be a blessing to engineering draftsmen.

@hsiungwang

**Comment by qazesz1** [comment]
你可以用otfcc [https://github.com/caryll/otfcc](url) 自行生成无hint字体

**Comment by be5invis** [comment]
Unhinted edition has released. Closing.

**Comment by asmwarrior** [comment]
> 



> 你可以用otfcc [https://github.com/caryll/otfcc](url) 自行生成无hint字体

Can I asked that how to use this tool? I know be5invis has unhinted version released, but I would like to use the otfcc tool on [CJK characters alignment issue in some applications · Issue #1 · jonz94/Sarasa-Gothic-Nerd-Fonts](https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts/issues/1)'s version, because it has fixed the alignment issue.

Thanks.
