### ISSUE TITLE
“警” displays weird in sarasa-ui-sc-regular

### ISSUE THREAD

**Issue by mercury233** [be5invis/Sarasa-Gothic#265]
former version(0.17.0):
![image](https://user-images.githubusercontent.com/13391795/138619631-79f83f64-03b0-486e-b837-e97804bc4ced.png)

current version(0.34.7):
![image](https://user-images.githubusercontent.com/13391795/138619663-23aae769-92e4-4b9c-86eb-69ea5e399565.png)

**Comment by mercury233** [comment]
![image](https://user-images.githubusercontent.com/13391795/142966104-5b310462-2083-4b43-ac1f-197a2d66fb08.png)
The 14px render of '上' in freetype is unacceptable, any change we can fix this?

**Comment by mwgamera** [comment]
This isn't a problem with just a single glyph. On the screenshots above you can also see 言 and 后 looking particularly bad and others blurrier than desirable too.
Looks like something is wrong with hinting under FreeType: only a few points are moved along the vertical axis making many horizontal strokes slanted or worse. As if the hinting program had aborted in the middle without ever reaching IUP or something. (I have no idea how to debug it.) Most points are not moved from their original unhinted positions.

Affected are *all* the stylistic and orthographic variants of Sarasa since the version **0.18.8**.
The last released version that rendered correctly was 0.18.7.

Here's what ftgrid shows for 警 in UI SC from 0.18.7, 0.18.8, and 0.35.1:
![ftgrid-0.18.7](https://user-images.githubusercontent.com/903892/143003248-dd2c9a8b-c349-482a-9435-2bf28742fee7.png) ![ftgrid-0.18.8](https://user-images.githubusercontent.com/903892/143003252-67cae6d1-e705-4cc8-b794-8664b1351f56.png) ![ftgrid-0.35.1](https://user-images.githubusercontent.com/903892/143003254-ae7584d4-8f9f-451d-a57a-e9f0c6842bea.png)

Assortment of badly hinted glyphs from Gothic HC from 0.35.0 and 0.18.8 release:
![ftstring-0.35.0](https://user-images.githubusercontent.com/903892/143003363-78dc5aa6-9923-415e-baf6-6887d69d5842.png)
![ftstring-0.18.8](https://user-images.githubusercontent.com/903892/143003359-f406b172-cf7c-4a6a-af8d-afc1ac6eedea.png)

Here from 0.18.7 for comparison:
![ftstring-0.18.7](https://user-images.githubusercontent.com/903892/143003452-ea89a7e3-7f19-4496-88a2-a9f7ec40ff42.png)

The problem occurs when rendered with recent versions of FreeType in hinting/antialiasing modes that make use of TrueType interpreter, but without difference whether using v35 or v40 one.
However, the problem doesn't appear when using very old versions of FreeType (broken in FreeType 2.8.1 and 2.11.0 but works well in 2.6.3), but I also looked at "show grid fit" option of FontForge and it shows different, but just as badly fit outline there.

**Comment by mwgamera** [comment]
The 0.35.1 release was still affected, but I can't reproduce it with 0.35.2.
