### ISSUE TITLE
Font version is not correct in 0.36.3 dist package.

### ISSUE THREAD

**Issue by deae** [be5invis/Sarasa-Gothic#286]
I just download the latest sarasa-gothic-ttc-0.36.3.7z. where I unpack the 7z, I open the font preview, and the version is 0.36.2. 

os: windows
btw  the ttf package has the same problem.

**Comment by win98se** [comment]
If you have another version of the same font installed, you will see the current version of the installed font instead of the version of the font file you're viewing.

This seems to be a bug in the font viewer.

Instead, you should check the Details tab of the font files' Properties dialog, as shown -
![image](https://user-images.githubusercontent.com/11819816/168984965-9dcb92d3-6548-487a-80a5-1493cdc837d5.png)
