### ISSUE TITLE
Add the Nerd Fonts support

### ISSUE THREAD

**Issue by syhily** [be5invis/Sarasa-Gothic#379]
As the Sarasa Gothic Font is a programming font that supports CJK characters, I would like to request the addition of [Nerd Fonts](https://www.nerdfonts.com). This icon set has been utilized in various terminal editors, and incorporating it will enhance the usability of the Sarasa Gothic Font.

**Comment by abceleung** [comment]
As an alternative, you can patch in nerd font by yourself. It is not a difficult process, just one line of Docker script:
https://github.com/ryanoasis/nerd-fonts?tab=readme-ov-file#font-patcher

Another option would be use a terminal emulator that supports fallback fonts (I think this is the term for it). I think Konsole (on KDE), Wezterm (has nerd font built-in) and Windows Terminal (See https://github.com/microsoft/terminal/pull/16821) can support this

**Comment by nerditation** [comment]
you can download readily patched fonts from this [repo](https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts). also, for Windows users, you can use the scoop [bucket](https://github.com/jonz94/scoop-sarasa-nerd-fonts), for MacOS users, you can use the homebrew [tap](https://github.com/jonz94/homebrew-sarasa-nerd-fonts)

there's a catch though, since the  unified CJK character set is very huge, the merged glyphs could hit the 64K limit of true type fonts, so some glyphs must be removed. see jonz94/Sarasa-Gothic-Nerd-Fonts#27 for details.
