### ISSUE TITLE
Iosevka中的星号问题

### ISSUE THREAD

**Issue by qianyeLC** [be5invis/Sarasa-Gothic#50]
你好 我使用的Saras-Gothic的等距版本等距"更纱黑体 SC"
使用星号的时候发现有两种样式,一种是位于中间位置,一种是位于中间偏上

![2](https://user-images.githubusercontent.com/8706932/44138797-aac27040-a0a7-11e8-9696-8938b1f74f2b.jpg)

我在Iosevka的原版仓库中看到示例图形, 也存在这种现象
![](https://raw.githubusercontent.com/be5invis/Iosevka/master/images/preview-all.png)
其中的

> wchar_t*" 

和 

> $*-+

中两处*号位置就是不一样的

这个是否正常设计?

**Comment by be5invis** [comment]
It is by design.
The Term variant does not have such behavior.

发自我的 iPhone

在 2018年8月15日，16:28，LCLancey <notifications@github.com<mailto:notifications@github.com>> 写道：


你好 我使用的Saras-Gothic的等距版本等距"更纱黑体 SC"
使用星号的时候发现有两种样式,一种是位于中间位置,一种是位于中间偏上

[2]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F8706932%2F44138797-aac27040-a0a7-11e8-9696-8938b1f74f2b.jpg&data=02%7C01%7C%7C22f8afedd06e4dbd5d3e08d60289023f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636699184798661383&sdata=HwGG%2FfuJtNQn%2ByiEfJRbRQPCHRqsEOB4%2FdYT4xuj0PY%3D&reserved=0>

我在Iosevka的原版仓库中看到示例图形, 也存在这种现象
[https://raw.githubusercontent.com/be5invis/Iosevka/master/images/preview-all.png]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fbe5invis%2FIosevka%2Fmaster%2Fimages%2Fpreview-all.png&data=02%7C01%7C%7C22f8afedd06e4dbd5d3e08d60289023f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636699184798661383&sdata=zEwAn8nPSmXFBi%2FK24a2tb9RmtBpgw1UoFRxfW8%2FN%2Fw%3D&reserved=0>
其中的

wchar_t*"
和
$-+
中两处号位置就是不一样的

这个是否正常设计?
