### ISSUE TITLE
Onenote2016中行距表现异常

### ISSUE THREAD

**Issue by TestSubject173** [be5invis/Sarasa-Gothic#64]
文字字体设定为更纱黑体、文字内容为中英文混合或仅包含英文时，于任意两个连续的英文字符之间依次执行换行、撤销、恢复动作后，稳定地出现行距扩大或行距不变但字符高度发生错位的情况。

**Comment by be5invis** [comment]
Looks like an OneNote issue rather than font issue. Office’ line height measurement is really strange.


________________________________
收件人: TestSubject173 <notifications@github.com>
发送时间: 星期日, 十二月 2, 2018 23:49
收件人: be5invis/Sarasa-Gothic
抄送: Subscribed
主题: [be5invis/Sarasa-Gothic] Onenote2016中行距表现异常 (#64)


文字字体设定为更纱黑体、文字内容为中英文混合或仅包含英文时，于任意两个连续的英文字符之间依次执行换行、撤销、恢复动作后，稳定地出现行距扩大或行距不变但字符高度发生错位的情况。

―

**Comment by TestSubject173** [comment]
其他字体在测试时都没有出现类似问题，除了 Iosevka

**Comment by be5invis** [comment]
I will file a bug to Office team. You can close now.


________________________________
收件人: TestSubject173 <notifications@github.com>
发送时间: 星期日, 十二月 2, 2018 23:57
收件人: be5invis/Sarasa-Gothic
抄送: Belleve Invis; Comment
主题: Re: [be5invis/Sarasa-Gothic] Onenote2016中行距表现异常 (#64)


其他字体在测试时都没有出现类似问题，除了 Iosevka

―

**Comment by bao-qian** [comment]
any update for this or https://github.com/be5invis/Iosevka/issues/197 ?

**Comment by Yohoa** [comment]
嗨！
我遇到了类似的问题；不仅出现在OneNote 2016 中。如果在Foxit PDF 的“打字机”（也就是页面注释）使用更纱黑体，同样会出现行距过大的问题。
![image](https://user-images.githubusercontent.com/17778268/86553256-ccbcda00-bf7c-11ea-9ff4-898be9f7151e.png)
可见上图
Many thanks!
